"""TikTok Photo Mode (slideshow) resolver.

yt-dlp has no extractor for TikTok's Photo Mode posts (`/photo/<id>` URLs - a
slideshow of images with a soundtrack, distinct from a normal TikTok video):
confirmed live 2026-08-28 against yt-dlp 2026.8.19, which raises a bare
"Unsupported URL" for one. Scraping TikTok's own post page doesn't work
either - the server-rendered `__UNIVERSAL_DATA_FOR_REHYDRATION__` blob that
would carry the item data is withheld behind TikTok's bot-check even with
curl_cffi Chrome impersonation (already used elsewhere in this repo for
TikTok - see requirements.txt), and TikTok's own private `/api/item/detail/`
endpoint needs a signed request (`X-Bogus`/`msToken`) generated by obfuscated
client-side JS with no public spec - a much bigger reverse-engineering target
than Instagram/Threads' private API or LinkedIn's plain og:image scrape.

What works: tikwm.com, a free public API already used by many open-source
TikTok downloaders, resolves a post (video or photo) server-side and hands
back direct, presigned CDN media URLs - no auth needed. Confirmed live
against a real TikTok Photo Mode post (4 images). This is the one resolver
in this repo that depends on a third-party service rather than talking to
the platform directly (owner decision, 2026-08-28, after reverse-engineering
TikTok's own endpoints hit a wall) - accepted because Photo Mode has no
other viable path today. The yt-dlp video path (the overwhelming majority of
TikTok links) is completely unaffected: callers only reach this after yt-dlp
has already failed, so a tikwm.com outage never slows down a normal video
download.
"""

import json
import urllib.parse
import urllib.request

TIKWM_UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)

_API_URL = "https://www.tikwm.com/api/?url="


class TikTokPhotoError(Exception):
    """tikwm.com couldn't resolve this post as a Photo Mode slideshow -
    either it's a normal video (no "images"), the post is deleted/private,
    or tikwm.com itself is unavailable."""


def fetch_tiktok_photo_post(url):
    # Returns {"title": str, "items": [{"kind": "image", "url", "thumbnail"}, ...]}
    # - same shape backend.instagram.instagram_check_response expects, so a
    # TikTok Photo Mode post renders exactly like an Instagram carousel (one
    # image -> type:"video", several -> type:"playlist").
    req = urllib.request.Request(_API_URL + urllib.parse.quote(url, safe=""), headers={"User-Agent": TIKWM_UA})
    with urllib.request.urlopen(req, timeout=20) as resp:
        payload = json.loads(resp.read().decode("utf-8", "replace"))

    data = payload.get("data") or {}
    images = data.get("images") or []
    if payload.get("code") != 0 or not images:
        raise TikTokPhotoError(
            f"tikwm.com could not resolve this TikTok post as a photo post "
            f"(code={payload.get('code')}, msg={payload.get('msg')})"
        )

    title = data.get("title") or "TikTok Photo Post"
    cover = data.get("cover")
    items = [{"kind": "image", "url": image_url, "thumbnail": cover} for image_url in images]
    return {"title": title, "items": items}
