"""TikTok resolver (video + Photo Mode), backed by tikwm.com.

Two distinct, unrelated yt-dlp gaps land here:

1. yt-dlp has no extractor at all for TikTok's Photo Mode posts (`/photo/<id>`
   URLs - a slideshow of images with a soundtrack, distinct from a normal
   TikTok video): confirmed live 2026-08-28 against yt-dlp 2026.8.19, which
   raises a bare "Unsupported URL" for one.
2. As of 2026-08-30, yt-dlp's own TikTok VIDEO extractor is *also* broken for
   every normal video post: confirmed live against 4 distinct real videos,
   every one fails with `Unable to extract universal data for rehydration` -
   even after yt-dlp solves TikTok's JS challenge, and even with a real
   logged-in browser session's cookies supplied (ruled out "just needs
   auth"). This is a known, currently open upstream issue
   (yt-dlp/yt-dlp#16199), unresolved since it was first reported in March
   2026 - part of an ongoing pattern of TikTok changing its page structure
   faster than yt-dlp's extractor catches up (see the repo's own MISTAKES.md
   entries on this file's history for the same pattern recurring over time).

Scraping TikTok's own post page doesn't work as a DIY fallback for either
gap - the server-rendered `__UNIVERSAL_DATA_FOR_REHYDRATION__` blob that
would carry the item data is withheld behind TikTok's bot-check even with
curl_cffi Chrome impersonation (already used elsewhere in this repo for
TikTok - see requirements.txt), and TikTok's own private `/api/item/detail/`
endpoint needs a signed request (`X-Bogus`/`msToken`) generated by obfuscated
client-side JS with no public spec - a much bigger reverse-engineering target
than Instagram/Threads' private API or LinkedIn's plain og:image scrape.

What works, for BOTH shapes: tikwm.com, a free public API already used by
many open-source TikTok downloaders, resolves a post (video or photo) server
-side and hands back direct, presigned CDN media URLs - no auth needed.
Confirmed live against a real TikTok Photo Mode post (4 images) and 4
distinct real video posts (4/4 succeeded, real watermark-free CDN URLs that
download real playable files).

**Design decision reversed 2026-08-30** (see MISTAKES.md): this module was
originally scoped to Photo Mode only, on the explicit assumption that "the
yt-dlp video path is completely unaffected... a tikwm.com outage never slows
down a normal video download" - that assumption held when this module was
written (2026-08-28) but stopped holding two days later once yt-dlp's own
video extraction broke for every tested video. tikwm.com is now the primary
resolution path for TikTok whenever yt-dlp fails, not a Photo-Mode-only
niche fallback - an explicit, accepted trade-off (this remains the one
resolver in this repo that depends on a third-party service rather than
talking to the platform directly), made because it is currently the only
path with live, verified evidence of actually working.
"""

import json
import time
import urllib.parse
import urllib.request

TIKWM_UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)

_API_URL = "https://www.tikwm.com/api/?url="
# tikwm.com's free tier caps at 1 request/second (confirmed live,
# 2026-08-30: a burst of requests in quick succession gets back
# {"code": -1, "msg": "Free Api Limit: 1 request/second."}). Retrying a
# couple of times after a brief pause turns a common, transient failure
# into a success instead of bubbling a confusing rate-limit message up to
# the user - this matters more now that this resolver is TikTok's primary
# fallback, not a rarely-hit Photo-Mode-only path.
_RATE_LIMIT_RETRIES = 2
_RATE_LIMIT_BACKOFF_SECONDS = 1.1


class TikTokResolverError(Exception):
    """tikwm.com couldn't resolve this TikTok post at all - the post is
    deleted/private, genuinely has no downloadable media, or tikwm.com
    itself is unavailable/rate-limiting after retries."""


def _fetch_tikwm_payload(url):
    req = urllib.request.Request(_API_URL + urllib.parse.quote(url, safe=""), headers={"User-Agent": TIKWM_UA})
    attempts = 0
    while True:
        with urllib.request.urlopen(req, timeout=20) as resp:
            payload = json.loads(resp.read().decode("utf-8", "replace"))
        is_rate_limited = payload.get("code") == -1 and "limit" in (payload.get("msg") or "").lower()
        if not is_rate_limited or attempts >= _RATE_LIMIT_RETRIES:
            return payload
        attempts += 1
        time.sleep(_RATE_LIMIT_BACKOFF_SECONDS)


def fetch_tiktok_post(url):
    # Returns {"title": str, "items": [...]}, matching
    # backend.instagram.instagram_check_response's expectation - a Photo
    # Mode post yields one {"kind": "image", ...} item per slide, a normal
    # video yields exactly one {"kind": "video", ...} item. Images win when
    # a post carries both (some Photo Mode posts also bundle a slideshow
    # "play" video with the soundtrack - the images are the actual content).
    payload = _fetch_tikwm_payload(url)
    data = payload.get("data") or {}
    if payload.get("code") != 0:
        raise TikTokResolverError(
            f"tikwm.com could not resolve this TikTok post (code={payload.get('code')}, msg={payload.get('msg')})"
        )

    images = data.get("images") or []
    play_url = data.get("play")
    if not images and not play_url:
        raise TikTokResolverError("tikwm.com resolved this post but it has no downloadable image or video")

    title = data.get("title") or "TikTok Post"
    cover = data.get("cover")
    if images:
        items = [{"kind": "image", "url": image_url, "thumbnail": cover} for image_url in images]
    else:
        items = [{"kind": "video", "url": play_url, "thumbnail": cover}]
    return {"title": title, "items": items}
